language: node_js
matrix:
  include:
    - node_js: "6.9.1"
    - node_js: "7"
    - node_js: "8"
dist: trusty
env:
  global:
    - ARTIFACTS_AWS_REGION=us-west-2
    - ARTIFACTS_S3_BUCKET=lighthouse-screenshots-debugging
    - secure: WNrQ6K8eS8/lVml6qz031oV3HQM0M3WB1+1K9DTbjlVSuYgzu3tLGCRWn67tF8+3AQWIRDXyHByONrGinWTm1teZA9SaTzuVhMrO7CHdsWTWsypQ0UqJ6H4mH/wJwJv/kW6OtQSQJGUTF8kEz33nDQVW+iFWxJx3Ow4egya6cb9D89TnUJ0FBLxYYS2DjNTbIMVBMBqSGyrd/Ww5CoYzKR96Y9jby5IId9TFFJqk3qFfXVh3Diy5TX8hUvqUpD48cfQpxE8cLZ/uOXtRsHjwMvekCSG7fNMlbQ9nJ4MmnIwhdvFrKbx1xS7g5FdRfyN+q3QcDxskytWYmtzREoRjU3N6ao8IGsXG88yXpK1bdGQ2BdNAg4IltQDGMKMzVC37sAFmXvI9S00TmWQOoAu5D4KuW9Gchc+syCpZ+umqPGePgfGryWBt0slOkFi3mixavL0kAr1kAbWbeGFBLEeX80NFFm+F2qOMuwPSsmVJ8bsgsEp0DkceyggAqb9VDyTq9ci8l/pTGTQfqbEBcXgS19BY2zDldvncfmHFisd13zHOYkqn+pi+Ta87xlskL93FOxQFn14avJo/5iNa2HmEh8vq/jBbocVr+Tt+T+OMzN/RFGBfzqU4T2K3rj9hG1cCgZFuVm+sdSuulzeUjV7y3rDAT3eAUwBnERCzwDhCpT0=
    - secure: UdWqkZHhU2PDMKleiL386FHI6S+N0PETDd5RWPBNM/YvMREWHyWeb3vZwsMqSVri1DNk8SqI2d0PC4/jLGKchRBqlO4+smuw9f09ihn+mGI67GFsyJu6UQ5/nz5eiUKx2ZRsuB8t8BbCGiOWh+UQUuHTEgAi8ndL+ml+Vy1XRpqbT49rOTKcr+G/4J+TyEjq+wRrpZMZmhYeX0EZAcofL8KYvgbV5jbkOnQV2oI0cyCO1FQxnIz9yopvwrMlKz/1jmKiRyJOj0YaKSJ5lWs0G2RFsWmXrEAgDAlOqoJ2QCTCM5M1Fnh+0oWPholN7X4Nj/USqxRlcGaUwDLh5RhcDlrFv+wC9iBIDIay3K1/IKndikkO8OP+tCYDlx2VQRX50LPUTEQzrXEbD6pFUl1ezLQCZPejX7R/HI5rOr8WcmZzKXtl1MP0h8YX1e9HX7gXBUB0RGwnTV/P+Q6WEcxN32T/xdwbYi/YQsXfzeL7fzF5PI5LnaAc141lhcUiILs9HwnEyB7gWWLlut+GNKfse6DrNkKc3I12TVVMbHWuP2waGuc1EMcMCyC/9lb17sk5q1gbIbAsSWki9mHtrJsk0KtriKY/uOFiK5W6Dno1ITbMqbTvIelMKgQPkjYmvqyLDhADRXQz9kxlSmxcdTG5dB9lOm6ubFdRmWEPhPumq4I=
cache:
  yarn: true
  directories:
    - node_modules
    - lighthouse-cli/node_modules
    - lighthouse-extension/node_modules
    - lighthouse-viewer/node_modules
    - /home/travis/.rvm/gems/
install:
  - yarn
  # travis can't handle the parallel install (without caches)
  - yarn run install-all:task:windows
before_script:
  - gem install travis-artifacts
  - export DISPLAY=:99.0
  - export CHROME_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - yarn build-all
script:
  - yarn bundlesize
  - yarn test-cli-formatting
  - yarn lint
  - yarn unit
  - yarn closure
  - yarn smoke
  - yarn smokehouse
  # _JAVA_OPTIONS is breaking parsing of compiler output. See #3338.
  - unset _JAVA_OPTIONS
  - yarn compile-devtools
before_cache:
  # the `yarn compile-devtools` task adds these to node_modules, which slows down caching
  - rm -rf ./node_modules/temp-devtoolsfrontend/
  - rm -rf ./node_modules/temp-devtoolsprotocol/
after_success:
  - ./lighthouse-core/scripts/generate-combined-coverage.sh
after_failure:
  - grep 'No screenshots' perf.json && travis-artifacts upload --path perf-0.trace.json
addons:
  chrome: stable
