name: DevTools

on:
  push:
    branches: [master]
  pull_request: # run on all PRs, not just PRs to a particular branch

jobs:
  integration:
    runs-on: macos-latest # while macbots are much slower, linux reliably crashes running this

    steps:
    - name: Set $DEPOT_TOOLS_PATH
      run: echo "DEPOT_TOOLS_PATH=$GITHUB_WORKSPACE/depot-tools" >> $GITHUB_ENV
    - name: Set $DEVTOOLS_PATH
      run: echo "DEVTOOLS_PATH=$GITHUB_WORKSPACE/devtools-frontend" >> $GITHUB_ENV
    - name: Set $BLINK_TOOLS_PATH
      run: echo "BLINK_TOOLS_PATH=$GITHUB_WORKSPACE/blink_tools" >> $GITHUB_ENV
    - name: Set $PATH
      run: echo "$DEPOT_TOOLS_PATH" >> $GITHUB_PATH

    - name: git clone
      uses: actions/checkout@v2
      with:
        path: lighthouse

    - name: Generate cache hash
      run: bash $GITHUB_WORKSPACE/lighthouse/.github/scripts/generate-devtools-hash.sh > cdt-test-hash.txt
    - name: Cache depot tools, devtools, blink tools and content shell
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.DEPOT_TOOLS_PATH }}
          ${{ env.DEVTOOLS_PATH }}
          ${{ env.BLINK_TOOLS_PATH }}
          ${{ github.workspace }}/lighthouse/.tmp/chromium-web-tests/content-shells
        # The number is how many times this hash key was manually updated to break the cache.
        key: ${{ runner.os }}-2-${{ hashFiles('cdt-test-hash.txt') }}

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: yarn --frozen-lockfile
      working-directory: ${{ github.workspace }}/lighthouse
    - run: yarn build-report
      working-directory: ${{ github.workspace }}/lighthouse
    - run: yarn build-devtools
      working-directory: ${{ github.workspace }}/lighthouse

    - name: Download depot tools
      run: bash $GITHUB_WORKSPACE/lighthouse/lighthouse-core/test/chromium-web-tests/download-depot-tools.sh
    - name: Download DevTools Frontend
      run: bash $GITHUB_WORKSPACE/lighthouse/lighthouse-core/test/chromium-web-tests/download-devtools.sh
    - name: Download Blink Tools
      run: bash $GITHUB_WORKSPACE/lighthouse/lighthouse-core/test/chromium-web-tests/download-blink-tools.sh
    - name: Download Content Shell
      run: bash $GITHUB_WORKSPACE/lighthouse/lighthouse-core/test/chromium-web-tests/download-content-shell.sh

    - name: Install python deps
      run: pip install six requests

    - name: Run Web Tests
      run: bash $GITHUB_WORKSPACE/lighthouse/lighthouse-core/test/chromium-web-tests/run-web-tests.sh

    - name: Print diff
      if: failure()
      run: find "$GITHUB_WORKSPACE/lighthouse/.tmp/layout-test-results/retry_3" -name '*-diff.txt' -exec cat {} \;
    - name: Upload results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: results
        path: ${{ github.workspace }}/lighthouse/.tmp/layout-test-results
    
    # Run smoke tests via DevTools
    - name: Define ToT chrome path
      run: echo "CHROME_PATH=/Users/runner/chrome-mac-tot/Chromium.app/Contents/MacOS/Chromium" >> $GITHUB_ENV
    - name: Install Chrome ToT
      working-directory: /Users/runner
      run: bash $GITHUB_WORKSPACE/lighthouse/lighthouse-core/scripts/download-chrome.sh && mv chrome-mac chrome-mac-tot
    - run: mkdir latest-run
      working-directory: ${{ github.workspace }}/lighthouse
    - name: yarn smoke --runner devtools
      # TODO: run on all tests.
      # - Current DevTools hangs on any page with a service worker.
      #   https://github.com/GoogleChrome/lighthouse/issues/13396
      # - Various other issues that needed investigation.
      run: yarn smoke --runner devtools --invert-match byte-efficiency byte-gzip dbw errors-infinite-loop lantern-idle-callback-short metrics-tricky-tti-late-fcp metrics-tricky-tti perf-budgets perf-fonts perf-frame-metrics perf-preload perf-trace-elements pwa-chromestatus pwa-svgomg pwa-rocks redirects-client-paint-server redirects-multiple-server redirects-single-server screenshot seo-tap-targets
      working-directory: ${{ github.workspace }}/lighthouse
